<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Packaging\**" />
    <EmbeddedResource Remove="Packaging\**" />
    <None Remove="Packaging\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Cards\BoosterPacks\SheriffCard.cs" />
    <Compile Remove="Cards\ShardSlinger.cs" />
    <Compile Remove="Cards\Template.cs" />
    <Compile Remove="MonoBehaviours\BountyDamageTracker.cs" />
    <Compile Remove="MonoBehaviours\CrystalShardModifier.cs" />
    <Compile Remove="MonoBehaviours\PlayerEffects\CADModulesEffect.cs" />
    <Compile Remove="MonoBehaviours\PlayerStatus\ArcaneDamageOverTime.cs" />
    <Compile Remove="Patches\CardPickPatch.cs" />
    <Compile Remove="Utils\GunUtils.cs" />
    <Compile Remove="Utils\PlayerCardResolver.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\gearup_asset" />
    <None Remove="Assets\gearup_cardarts" />
    <None Remove="Assets\gearup_game_effect" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\gearup_asset" />
    <EmbeddedResource Include="Assets\gearup_cardarts" />
    <EmbeddedResource Include="Assets\gearup_game_effect" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Cards\BoosterPacks\SheriffCard.cs" />
    <None Include="MonoBehaviours\BountyDamageTracker.cs" />
    <None Include="MonoBehaviours\PlayerEffects\CADModulesEffect.cs" />
    <None Include="Patches\CardPickPatch.cs" />
    <None Include="Utils\GunUtils.cs" />
    <None Include="Utils\PlayerCardResolver.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\Toolkit\BepInExx\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\Toolkit\BepInExx\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="CardChoiceSpawnUniqueCardPatch">
      <HintPath>..\..\Toolkit\Modding Libraries\Pykess-CardChoiceSpawnUniqueCardPatch\CardChoiceSpawnUniqueCardPatch.dll</HintPath>
    </Reference>
    <Reference Include="ModdingUtils">
      <HintPath>..\..\Toolkit\Modding Libraries\Pykess-ModdingUtils\ModdingUtils.dll</HintPath>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\Photon3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="PhotonChat">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\PhotonChat.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking.Demos">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\PhotonUnityNetworking.Demos.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking.Utilities">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\PhotonUnityNetworking.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="PhotonWebSocket">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\PhotonWebSocket.dll</HintPath>
    </Reference>
    <Reference Include="RarityLib">
      <HintPath>..\..\Toolkit\Modding Libraries\RarityLib.dll</HintPath>
    </Reference>
    <Reference Include="SonigonAudioEngine.Runtime">
      <HintPath>..\..\RoundMod AssetsPlus\Assets\Scripts\Mods\dlls\SonigonAudioEngine.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnboundLib">
      <HintPath>..\..\Toolkit\Modding Libraries\willis81808-UnboundLib\UnboundLib.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\..\..\SteamLibrary\steamapps\common\ROUNDS\Rounds_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UtilityCategories">
      <HintPath>..\..\Toolkit\Modding Libraries\UtilityCategories.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
